# doxygen-deploy.yml
name: doxygen-deploy

on:
  push:
    branches: [master] # Note: this needs to be set to your default branch
    # name (this might be "main" rather than "master")

jobs:
  # The job that will build testProject
  deploy-testProject:
    # Defines the operating system for the virtual machine
    runs-on: ubuntu-latest

    # A list of steps to follow to complete the build
    # (a list of commands to execute on the virtual machine)
    steps:
      # This is a predefined action that checks out a copy of your code
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Install doxygen
        run: sudo apt-get install -y doxygen
      
      # Run Doxygen on testDoxygen folder
      - name: Run Doxygen
        working-directory: ${{ github.workspace }}/testProject
        run: doxygen
      
      # Deploy html output from Doxygen to gh-pages branch
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.2.5
        with:
          # The branch the action should deploy to.
          branch: gh-pages
          # The folder the action should deploy.
          folder: ${{ github.workspace }}/testProject/html
